INSERT INTO `material_units` (`id`, `description`, `created_by`, `updated_by`, `deleted_at`, `created_at`, `updated_at`) VALUES
	(1, 'pcs.', 1, 1, NULL, NULL, NULL),
	(2, 'bags', 1, 1, NULL, NULL, NULL),
	(3, 'cu.m.', 1, 1, NULL, NULL, NULL),
	(4, 'rolls', 1, 1, NULL, NULL, NULL),
	(5, 'sheets', 1, 1, NULL, NULL, NULL),
	(6, 'box', 1, 1, NULL, NULL, NULL),
	(7, 'kgs.', 1, 1, NULL, NULL, NULL),
	(8, 'holes', 1, 1, NULL, NULL, NULL),
	(9, 'liters', 1, 1, NULL, NULL, NULL),
	(10, 'sq.m.', 1, 1, NULL, NULL, NULL),
	(11, 'meters', 1, 1, NULL, NULL, NULL),
	(12, 'sack', 1, 1, NULL, NULL, NULL),
	(13, 'month', 1, 1, NULL, NULL, NULL),
	(14, 'days', 1, 1, NULL, NULL, NULL),
	(15, 'pax', 1, 1, NULL, NULL, NULL),
	(16, 'l.s.', 1, 1, NULL, NULL, NULL),
	(17, 'tank', 1, 1, NULL, NULL, NULL),
	(18, 'gal.', 1, 1, NULL, NULL, NULL),
	(19, 'unit', 1, 1, NULL, NULL, NULL),
	(20, 'set', 1, 1, NULL, NULL, NULL),
	(21, 'ream', 1, 1, NULL, NULL, NULL),
	(22, 'bottle', 1, 1, NULL, NULL, NULL),
	(23, 'board feet', 1, 1, NULL, NULL, NULL),
	(24, 'can', 1, 1, NULL, NULL, NULL),
	(25, 'Pail', 1, 1, NULL, NULL, NULL),
	(26, 'lot', 1, 1, NULL, NULL, NULL),
	(27, 'drum', 1, 1, NULL, NULL, NULL);